import { addMonths } from 'date-fns/addMonths';

export const randomTravel = [
  // Los Angeles (LAX) - 17条数据 (California)
  {
    arrivalDate: addMonths(new Date(), 3), // 2025年7月8日
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX880', // 国泰航空 HKG -> LAX
    departureDate: addMonths(new Date(), 4), // 2025年8月8日
    departureCity: 'Los Angeles',
    departureFlight: 'CX881', // 国泰航空 LAX -> HKG
    locations: 'The Beverly Hills Hotel',
    address: '9641 Sunset Blvd',
    city: 'Beverly Hills',
    zipCode: '90210',
    phone: '(310) 276-2251',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA857', // 联合航空 HKG -> LAX
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA858', // 联合航空 LAX -> HKG
    locations: 'The Ritz-Carlton, Los Angeles',
    address: '900 W Olympic Blvd',
    city: 'Los Angeles',
    zipCode: '90015',
    phone: '(213) 743-8800',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX882', // 国泰航空 HKG -> LAX
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX883', // 国泰航空 LAX -> HKG
    locations: 'Waldorf Astoria Beverly Hills',
    address: '9850 Wilshire Blvd',
    city: 'Beverly Hills',
    zipCode: '90210',
    phone: '(310) 860-6666',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA869', // 联合航空 HKG -> LAX
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA870', // 联合航空 LAX -> HKG
    locations: 'The Langham Huntington, Pasadena',
    address: '1401 S Oak Knoll Ave',
    city: 'Pasadena',
    zipCode: '91106',
    phone: '(626) 568-3900',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX884', // 国泰航空 HKG -> LAX
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX885', // 国泰航空 LAX -> HKG
    locations: 'Four Seasons Hotel Los Angeles',
    address: '300 S Doheny Dr',
    city: 'Los Angeles',
    zipCode: '90048',
    phone: '(310) 273-2222',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX880',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX881',
    locations: 'The Westin Bonaventure Hotel',
    address: '404 S Figueroa St',
    city: 'Los Angeles',
    zipCode: '90071',
    phone: '(213) 624-1000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA857',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA858',
    locations: 'Hilton Los Angeles Airport',
    address: '5711 W Century Blvd',
    city: 'Los Angeles',
    zipCode: '90045',
    phone: '(310) 410-4000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX882',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX883',
    locations: 'The Peninsula Beverly Hills',
    address: '9882 S Santa Monica Blvd',
    city: 'Beverly Hills',
    zipCode: '90212',
    phone: '(310) 551-2888',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA870',
    locations: 'InterContinental Los Angeles Downtown',
    address: '900 Wilshire Blvd',
    city: 'Los Angeles',
    zipCode: '90017',
    phone: '(213) 688-7777',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX884',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX885',
    locations: 'Shutters on the Beach',
    address: '1 Pico Blvd',
    city: 'Santa Monica',
    zipCode: '90405',
    phone: '(310) 458-0030',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX880',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX881',
    locations: 'Hotel Bel-Air',
    address: '701 Stone Canyon Rd',
    city: 'Los Angeles',
    zipCode: '90077',
    phone: '(310) 472-1211',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA857',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA858',
    locations: 'The Hollywood Roosevelt',
    address: '7000 Hollywood Blvd',
    city: 'Los Angeles',
    zipCode: '90028',
    phone: '(323) 856-1970',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX882',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX883',
    locations: 'SLS Hotel, a Luxury Collection Hotel',
    address: '465 S La Cienega Blvd',
    city: 'Los Angeles',
    zipCode: '90048',
    phone: '(310) 247-0400',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA870',
    locations: 'JW Marriott Los Angeles L.A. LIVE',
    address: '900 W Olympic Blvd',
    city: 'Los Angeles',
    zipCode: '90015',
    phone: '(213) 765-8600',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX884',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX885',
    locations: 'The London West Hollywood',
    address: '1020 N San Vicente Blvd',
    city: 'West Hollywood',
    zipCode: '90069',
    phone: '(310) 854-1111',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'CX880',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'CX881',
    locations: 'Viceroy L’Ermitage Beverly Hills',
    address: '9291 Burton Way',
    city: 'Beverly Hills',
    zipCode: '90210',
    phone: '(310) 278-3344',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'Los Angeles',
    arrivalFlight: 'UA857',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'Los Angeles',
    departureFlight: 'UA858',
    locations: 'Chateau Marmont',
    address: '8221 Sunset Blvd',
    city: 'Los Angeles',
    zipCode: '90046',
    phone: '(323) 656-1010',
    province: 'California',
  },

  // New York (JFK) - 17条数据 (New York)
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830', // 国泰航空 HKG -> JFK
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831', // 国泰航空 JFK -> HKG
    locations: 'The Plaza Hotel',
    address: '768 5th Ave',
    city: 'New York',
    zipCode: '10019',
    phone: '(212) 759-3000',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The Ritz-Carlton New York, Central Park',
    address: '50 Central Park S',
    city: 'New York',
    zipCode: '10019',
    phone: '(212) 308-9100',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX844',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX845',
    locations: 'Four Seasons Hotel New York',
    address: '57 E 57th St',
    city: 'New York',
    zipCode: '10022',
    phone: '(212) 758-5700',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831',
    locations: 'The Peninsula New York',
    address: '700 5th Ave',
    city: 'New York',
    zipCode: '10019',
    phone: '(212) 956-2888',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The St. Regis New York',
    address: '2 E 55th St',
    city: 'New York',
    zipCode: '10022',
    phone: '(212) 753-4500',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX844',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX845',
    locations: 'Waldorf Astoria New York',
    address: '301 Park Ave',
    city: 'New York',
    zipCode: '10022',
    phone: '(212) 355-3000',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831',
    locations: 'The Carlyle, A Rosewood Hotel',
    address: '35 E 76th St',
    city: 'New York',
    zipCode: '10021',
    phone: '(212) 744-1600',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The Lowell Hotel',
    address: '28 E 63rd St',
    city: 'New York',
    zipCode: '10065',
    phone: '(212) 838-1400',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX844',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX845',
    locations: 'The Mark Hotel',
    address: '25 E 77th St',
    city: 'New York',
    zipCode: '10075',
    phone: '(212) 744-4300',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831',
    locations: 'The Chatwal, a Luxury Collection Hotel',
    address: '130 W 44th St',
    city: 'New York',
    zipCode: '10036',
    phone: '(212) 764-6200',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The Bowery Hotel',
    address: '335 Bowery',
    city: 'New York',
    zipCode: '10003',
    phone: '(212) 505-9100',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX844',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX845',
    locations: 'The Greenwich Hotel',
    address: '377 Greenwich St',
    city: 'New York',
    zipCode: '10013',
    phone: '(212) 941-8900',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831',
    locations: 'The NoMad Hotel',
    address: '1170 Broadway',
    city: 'New York',
    zipCode: '10001',
    phone: '(212) 796-1500',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The Beekman, A Thompson Hotel',
    address: '123 Nassau St',
    city: 'New York',
    zipCode: '10038',
    phone: '(212) 233-2300',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX844',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX845',
    locations: 'The William Vale',
    address: '111 N 12th St',
    city: 'Brooklyn',
    zipCode: '11249',
    phone: '(718) 631-8400',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX830',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX831',
    locations: '1 Hotel Central Park',
    address: '1414 6th Ave',
    city: 'New York',
    zipCode: '10019',
    phone: '(212) 703-2001',
    province: 'New York',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'New York',
    arrivalFlight: 'CX840',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'New York',
    departureFlight: 'CX841',
    locations: 'The Standard, High Line',
    address: '848 Washington St',
    city: 'New York',
    zipCode: '10014',
    phone: '(212) 645-4646',
    province: 'New York',
  },

  // San Francisco (SFO) - 16条数据 (California)
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872', // 国泰航空 HKG -> SFO
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873', // 国泰航空 SFO -> HKG
    locations: 'The Ritz-Carlton, San Francisco',
    address: '600 Stockton St',
    city: 'San Francisco',
    zipCode: '94108',
    phone: '(415) 296-7465',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'UA869', // 联合航空 HKG -> SFO
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'UA870', // 联合航空 SFO -> HKG
    locations: 'Fairmont San Francisco',
    address: '950 Mason St',
    city: 'San Francisco',
    zipCode: '94108',
    phone: '(415) 772-5000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX892', // 国泰航空 HKG -> SFO
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX893', // 国泰航空 SFO -> HKG
    locations: 'Four Seasons Hotel San Francisco',
    address: '757 Market St',
    city: 'San Francisco',
    zipCode: '94103',
    phone: '(415) 633-3000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873',
    locations: 'The St. Regis San Francisco',
    address: '125 3rd St',
    city: 'San Francisco',
    zipCode: '94103',
    phone: '(415) 284-4000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'UA870',
    locations: 'Palace Hotel, a Luxury Collection Hotel',
    address: '2 New Montgomery St',
    city: 'San Francisco',
    zipCode: '94105',
    phone: '(415) 512-1111',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX892',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX893',
    locations: 'The Westin St. Francis San Francisco',
    address: '335 Powell St',
    city: 'San Francisco',
    zipCode: '94102',
    phone: '(415) 397-7000',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873',
    locations: 'Hilton San Francisco Union Square',
    address: '333 O’Farrell St',
    city: 'San Francisco',
    zipCode: '94102',
    phone: '(415) 771-1400',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'UA870',
    locations: 'InterContinental San Francisco',
    address: '888 Howard St',
    city: 'San Francisco',
    zipCode: '94103',
    phone: '(415) 616-6500',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX892',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX893',
    locations: 'JW Marriott San Francisco Union Square',
    address: '515 Mason St',
    city: 'San Francisco',
    zipCode: '94102',
    phone: '(415) 771-8600',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873',
    locations: 'Hotel Nikko San Francisco',
    address: '222 Mason St',
    city: 'San Francisco',
    zipCode: '94102',
    phone: '(415) 394-1111',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'UA870',
    locations: 'The Clancy',
    address: '299 2nd St',
    city: 'San Francisco',
    zipCode: '94105',
    phone: '(415) 947-0700',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX892',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX893',
    locations: 'San Francisco Marriott Marquis',
    address: '780 Mission St',
    city: 'San Francisco',
    zipCode: '94103',
    phone: '(415) 896-1600',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873',
    locations: 'The Huntington Hotel',
    address: '1075 California St',
    city: 'San Francisco',
    zipCode: '94108',
    phone: '(415) 474-5400',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'UA869',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'UA870',
    locations: 'Argonaut Hotel',
    address: '495 Jefferson St',
    city: 'San Francisco',
    zipCode: '94109',
    phone: '(415) 563-0800',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX892',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX893',
    locations: 'Hotel Emblem San Francisco',
    address: '562 Sutter St',
    city: 'San Francisco',
    zipCode: '94102',
    phone: '(415) 433-4434',
    province: 'California',
  },
  {
    arrivalDate: addMonths(new Date(), 3),
    arrivalCity: 'San Francisco',
    arrivalFlight: 'CX872',
    departureDate: addMonths(new Date(), 4),
    departureCity: 'San Francisco',
    departureFlight: 'CX873',
    locations: 'The Battery',
    address: '717 Battery St',
    city: 'San Francisco',
    zipCode: '94111',
    phone: '(415) 230-8000',
    province: 'California',
  },
];
